### ISSUE TITLE
Just ideas and feedback

### ISSUE THREAD

**Issue by grigio** [meteorhacks/meteord#1]
1. Is Ubuntu as baseimage really necessary?
   the official [Docker NodeJS images](https://github.com/docker-library/official-images/blob/master/library/node) seems to be build around Debian, which have a smaller footprint
2. The official way to install meteor doesn't allow to specify directly the release you want
   but is possible to [live patch](https://github.com/grigio/docker-meteor/blob/master/Dockerfile#L10) that script.
3. Meteor already embeds NodeJS
   It seems a good idea to [use that](https://github.com/grigio/docker-meteor/blob/master/meteor-run.sh#L2), at least if you already have meteor in that image to run `meteor build`.
   Also because it isn't guareanteed meteor would work with latest NodeJs or IOjs release

**Comment by arunoda** [comment]
Using debian is a good idea. Will do that.

We don't need to install a specific release of Meteor. Meteor will do it itself. Let him do his job :)

This docker image does carry Meteor binaries or anything related. It uses Meteor for just only build the bundle. After that it won't have Meteor. (and we don't need to)

**Comment by arunoda** [comment]
Added debian support with #2

**Comment by arunoda** [comment]
For the 3) We are currently installing node version 0.10.33 and it's fixed. So, this docker image works. We can do a better job at finding the npm version. But for now, I'll update it manually.

**Comment by arunoda** [comment]
Hope we can close this.
