### ISSUE TITLE
No npm install? How are we supposed to deal with installing npms?

### ISSUE THREAD

**Issue by ciwolsey** [meteorhacks/meteord#103]
When deploying an app I'm getting unresolved modules. I've seen there are already some closed issues on this subject and even a fork that adds "npm install", but why isn't this in meteord? How are we supposed to run apps that use npms without the fork? Seems pretty crazy.

**Comment by jshimko** [comment]
There's not much action around here these days.  You may want to just fork the repo and make the changes you need so you're not depending on someone else for updates (probably just need to add an `npm i` [like I did here](https://github.com/jshimko/meteord/blob/meteor-one-three/base/scripts/lib/build_app.sh#L11-L15)).
