### ISSUE TITLE
How to pass a settings JSON file to meteor? env METEOR_SETTINGS does't work.

### ISSUE THREAD

**Issue by olivierpascal** [meteorhacks/meteord#16]

**Comment by arunoda** [comment]
env METEOR_SETTINGS works and we are using it multiple projects.
Why it's not working?

**Comment by olivierpascal** [comment]
Hi arunoda! You are right. I was struggled with a METEOR_SETTINGS that did not include a public section and my test was to console.log Meteor.settings from the client console. My mistake!

**Comment by olivierpascal** [comment]
@arunoda I have found a pretty elegant solution to automatically deploy settings, inspired from https://forums.meteor.com/t/use-npm-require-to-load-meteor-settings/2936.

To load settings dynamically at runtime, I use a script like this one in server/lib/settings.coffee:

```
_path = Npm.require 'path'

Meteor.startup ->
  envProfile = process.env.METEOR_APP_PROFILE
  envRootUrl = process.env.ROOT_URL
  envPwd     = process.env.PWD

  if envProfile
    #
    # Construct settings file base path

    assetsPath = null
    if !envRootUrl || envRootUrl == 'http://localhost:3000/'
      assetsPath = 'private'
    else
      assetsPath = _path.join 'programs', 'server', 'assets', 'app'

    path = _path.join envPwd, assetsPath, 'profiles', envProfile + '.json'

    #
    # Setup meteor settings from a file on the server
    # and expose public settings to the client if needed

    Meteor.settings = Npm.require path

    if Meteor.settings && Meteor.settings.public
      __meteor_runtime_config__.PUBLIC_SETTINGS = Meteor.settings.public
```

Then in my docker container, I just set the envvar METEOR_APP_PROFILE that define the name of the settings file to load.

And to deploy an app, I just upload the bundle and redeploy the service.
