### ISSUE TITLE
When using npm-container package build will fail

### ISSUE THREAD

**Issue by javdl** [meteorhacks/meteord#17]
Hi,

whenever Iḿ using the package: npm-container the build will fail:

```
/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: EXDEV, rename '/app/.meteor/local/isopacks/npm-container'
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as rename] (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:1350:24)
```

**Comment by arunoda** [comment]
May be this is because of the use of boot2docker. Since it's running a on Virtual Box assigned driver. I'm quite not sure about a fix.

I hope this works pretty well on Linux? (on a actual Linux Host)

**Comment by arunoda** [comment]
Try the last version:

Use `meteorhacks/meteord:onbuild` as the base image. 
See README for docs.

**Comment by javdl** [comment]
Thanks Arunoda, this now works great! The NPM error is gone.

FYI, I have also built a working image for using Meteor + Phusion Passenger in Docker. The only thing thatś missing is building the meteor app from inside the container. So first you will have to build the Meteor app on your local machine;

``` shell
meteor build --architecture=os.linux.x86_64 --directory .deploy
```

then build the Docker image. Might be useful for you to play around with, maybe do some comparisons against your meteor-cluster package.
https://github.com/Joostvanderlaan/meteor-docker-passenger
