### ISSUE TITLE
Compatible with spiderable?

### ISSUE THREAD

**Issue by olivierpascal** [meteorhacks/meteord#19]
Thank you for this great work. Just noticed that when I access to my website with `?_escaped_fragment_=`, I have an error 500: "Internal Server Error".

Logs say:

```
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at Object.Package [as handle] (packages/spiderable/spiderable_server.js:105:1)
    at next (/bundle/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at middleware (packages/oauth/oauth_server.js:157:1)
    at packages/oauth/oauth_server.js:146:1
```

So the website cannot be indexed by Google, nor used with Adwords.

**Comment by arunoda** [comment]
Actually, it works.
This is a memory issue. Your docker container does not have enough memory to spawn phantomjs. 
Where are your running your container?

PhantomJS requires at least 10MB for each instance. So, if someone is crawling 100 pages at once, you need to have 1000MB in your container.

There is an another issue with spiderable under docker. See: https://github.com/meteor/meteor/issues/2429

**Comment by olivierpascal** [comment]
Thank you for your time arunoda. Actually it turns out to be a symptom of another problem: https://github.com/iron-meteor/iron-router/issues/1192 You are right, it's related to the spiderable package. The strange thing is that it happens only with docker. I keep investigating.

**Comment by olivierpascal** [comment]
Well, I've progressed a little bit on this issue. When I deploy with --debug, I see an error from meteor-pages that use .bind(), that's not supported by phantomjs < 2. Do you plan to upgrade phantomjs version to 2?

**Comment by arunoda** [comment]
Yes. `.bind()` is a long long issue of phantomjs. I'm more than happy to upgrade to phantomjs 2. But the problem is it's not stable yet and it's still on 2.0.

I'm not yet happy to replace it yet!

**Comment by olivierpascal** [comment]
Well noted. So I think this issue is closed for me. Without meteor-pages, no more issue.

BTW is there a simple way to update phantomjs in my container and make this modification persistent? Or should I have to fork your github repo, edit your script, publish on docker hub and create a new container from this forked image?

**Comment by arunoda** [comment]
Okay. Right now, you need to fork this and change here: https://github.com/meteorhacks/meteord/blob/master/base/scripts/lib/install_phantomjs.sh

But, we'll have something simple soon.

**Comment by daslicht** [comment]
Hello,
I still get the internal server error after running: 
https://github.com/meteorhacks/meteord/blob/master/base/scripts/lib/install_phantomjs.sh
any fix?
