### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by nevson** [meteorhacks/meteord#22]
Is it possible to provide a meteor app also via HTTPS? So far I can see only that the HTTP port 80 gets exported. Would really appreciate if that's possible as HTTP is really a security issue.

**Comment by levino** [comment]
How about using a load balancer to encrypt? This guide was pretty useful to me: https://support.tutum.co/support/solutions/articles/5000050235-load-balancing-a-web-service

**Comment by nevson** [comment]
@Levino Thanks for the feedback! You mean I should use the [haproxy](https://github.com/tutumcloud/haproxy) from tutum? If it can be run on my own docker host server and doesn't require any external connection to the tutum cloud or other public internet servers then this would be an option. 

It wonders me a bit but it seems like the Meteor server doesn't support HTTPS out of the box or? Using an extra proxy docker container just for redirecting HTTP to HTTPS seems to be a bit over the top. It would be a lot more straight forward if Meteor supports HTTPS by default... but that's nothing that can be influenced by this meteord container though.

**Comment by levino** [comment]
Na, just configure any tutum proxy in the way you need it. Tutum just makes it very easy. But you can link the meteor container into any haproxy container of your choice and have haproxy ssl encrypt it all.

There is no need whatsoever to do ssl in the meteor container. Think modular. One service, one task.

**Comment by nevson** [comment]
I got now the tutum proxy working by linking it into the meteor container and it works as expected, thanks for the tip!

This is more a general Meteor critic, but imho HTTPS must be a key/core feature and should be preferred always over HTTP. The haproxy solution is working but it adds between the linked container an additional HTTP overhead that could be avoided (in my case).

Anyhow, thanks a lot :)
