### ISSUE TITLE
Dont hard code port 80

### ISSUE THREAD

**Issue by levino** [meteorhacks/meteord#23]
I want to run the app on port 3000. As far as I can see the environment variable "PORT" will not be respected. I would love to be able to set 

``` bash
-e PORT=3000
```

What do you say?

**Comment by arunoda** [comment]
We disabled it purposely. You can expose it with any port as you like.

**Comment by levino** [comment]
I am using tutum. There I can set up load balancers that route traffic based on hostnames to different connected containers. To find the services, I have to declare the port that the containers are using internally, not externally.

What is the purpose of disabling it?

**Comment by arunoda** [comment]
Okay. That's seems an issue. Okay, then we should allow it.
Here's the code related to that:
https://github.com/meteorhacks/meteord/blob/master/base/scripts/run_app.sh#L34

Would you mind sending a PR.
Set it to port 80 if there is no PORT env variable in.

**Comment by levino** [comment]
Yeah, found it already and just trying it out locally and on tutum. Will send PR later.

**Comment by Kielan** [comment]
Thanks for making this issue. Definitely a critical piece to be hardcoded which can so easily be overlooked and cause port problems.

For example this ovverrides any Docker env variables.

**Comment by arunoda** [comment]
@Kielan I didn't get your point. Sorry.

Are you saying, hardcoded port is a good idea or bad?

**Comment by levino** [comment]
He is saying that this is bad practice. What if someone creates a container based on this image, that runs a second app, where the environment variable "port" is used? It would silently be overwritten, which of course is not anticipated.

**Comment by arunoda** [comment]
This is fixed now. Now you can expose the env `PORT`.
