### ISSUE TITLE
Setting MONGO_URL via linking

### ISSUE THREAD

**Issue by mstn** [meteorhacks/meteord#4]
Currently MONGO_URL is set as environment variable. This is useful when MongoDB url is fixed (e.g. an external cloud service). However, if another container is used for MongoDB, then the url can change after restarting (right?) and it could be hard to fetch the correct IP address automatically. In this case I think Docker linking is the best option. I tried to override without success the default entrypoint of your script and setting the environment var through linking before calling "run" script. Hence I think the original Dockerfile should be changed in order to handle the two cases. Since I am new to Docker, I wonder if you have already in mind a strategy or if there is a workaround for the current implementation. Thanks.

**Comment by arunoda** [comment]
Yes linking is a good options and we should have it.
You can add that logic into here: https://github.com/meteorhacks/meteord/blob/master/scripts/run_app.sh

Some steps to follow:
- link the mongo container as "mongo"
- check if it's linked (via env. vars)
- If it's build a env var from it

I'm not quire sure how to pass the mongo oplog URL.

**Comment by mstn** [comment]
Hi, thanks for your answer.

Some env vars are created after linking, for example MONGO_PORT_27017_TCP_ADDR (also for oplog). Actually I do not like this part _27017_ since it depends on the port number chosen in mongo container. I need to understand if it is possible to use the symbolic name "mongo" instead.

I'll let you know when a pr is ready.

**Comment by mstn** [comment]
Just for reference. I started working here https://github.com/mstn/meteord
It is almost done. I am going to test it a bit before creating the pull request.

**Comment by arunoda** [comment]
I think, there is no good way to link a production mongo deployment with replicas and oplog.
So, we should set the URLs manually.
