### ISSUE TITLE
New to docker

### ISSUE THREAD

**Issue by ghost** [meteorhacks/meteord#50]
I'm stuck on step 2, it just says create my app, or visit docs.meteor.com then crashes afterwards. Am I missing something?

**Comment by ghost** [comment]
To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

=> Errors while initializing project:

While selecting package versions:
error: unknown package in top-level dependencies: errors

The command '/bin/sh -c bash $METEORD_DIR/on_build.sh' returned a non-zero code: 1
 I'm getting this error.

**Comment by j6k4m8** [comment]
This sounds like you're not showing it a valid meteor project directory. Not a docker issue, so I _think_ this is out-of-scope for this repository..?

**Comment by jacobdr** [comment]
I am also experiencing a freeze during the Docker build process

```
Jacob@Jacobs-MBP-3:~/...ne/approvalsApp$ docker build -t cdl/sales_demo_test .
Sending build context to Docker daemon 482.5 MB
Sending build context to Docker daemon
Step 0 : FROM meteorhacks/meteord:onbuild
# Executing 2 build triggers
Trigger 0, COPY ./ /app
Step 0 : COPY ./ /app
Trigger 1, RUN bash $METEORD_DIR/on_build.sh
Step 0 : RUN bash $METEORD_DIR/on_build.sh
 ---> Running in cc4af5682c4f
Downloading Meteor distribution

Meteor 1.2.0.2 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

INFO[0724] The command [/bin/sh -c bash $METEORD_DIR/on_build.sh] returned a non-zero code: 1
```

I am using the Meteor Typescript compiler, so not sure if that intermediary step is affecting the build process or now...

**Comment by ghost** [comment]
It was my package named 'errors' whose causing the error. That was hard to find hehe. I removed it and it worked. Thanks!
