### ISSUE TITLE
Error: /opt/meteord/run_app.sh: line 44:    18 Killed                  node main.js

### ISSUE THREAD

**Issue by brugnara** [meteorhacks/meteord#58]
After a couple of hours the app is killed and the only log I found is this one:

```
/opt/meteord/run_app.sh: line 44:    18 Killed                  node main.js
```

This happened 2 times in a day. Any chance to get a more detailed log about this? Many thanks.

**Comment by alur222** [comment]
We are also experiencing this issue. Currently, I restart the service manually. :(

**Comment by brugnara** [comment]
I think this is a problem with kadira, maybe an old version but I am not sure. 
Actually I am using the `restart` flag: https://docs.docker.com/engine/reference/run/#restart-policies-restart

**Comment by alur222** [comment]
How did you solve it? I am very new to Docke, sorry.

**Comment by brugnara** [comment]
you have to run the container with the flag `--restart=always` and this will restart the container in case of errors. Are you using kadira in your meteor application?

**Comment by alur222** [comment]
Yep, I am using meteorhacks:kadira, kadira:blaze-layout and kadira:flow-router. How is this related to kadira? I really wanted to know. thanks

**Comment by brugnara** [comment]
I have noticed that kadira after a while throws an exception causing the
program to be killed. I don't know why. I have closed this issue because
the problem is not related with meteord.

Il giorno Ven 4 Dic 2015 02:52 Raul Torrefiel Jr. notifications@github.com
ha scritto:

**Comment by bompi88** [comment]
I'm getting this too, but it is not the cause of kadira. I'm indexing documents to Elasticsearch. Maybe this behaviour is caused by `HTTP`module somehow?

**Comment by alur222** [comment]
I dont know what really happend to our app but I just upgraded my nodes from 1gb to 2gb and it solved this issue. Please try it. I hope it helps.

**Comment by bompi88** [comment]
Thanks @skemb321 :) That's actually what I ended up doing. I found out that my docker machine only had 1g memory located, and I was running 3 containers in it. I increased its memory, together setting `ES_HEAP_SIZE` to 2g and the container memory to 3g with the `-m` switch. Looks like Elasticsearch did not have resources enough to process all the indexing requests while indexing about 22k documents.
