### ISSUE TITLE
EXPOSE port 80?

### ISSUE THREAD

**Issue by jhgaylor** [meteorhacks/meteord#6]
I spent a good long while trying to make my fork work and ultimately I just had to add `EXPOSE 80` to the dockerfile.  I made a few other alterations that would exclude a direct pull request, but I can send a PR for just this one line if you'd like.  Without the line I was getting connection refused from external hosts such as my browser.

**Comment by arunoda** [comment]
Okay. Send me that.

**Comment by arunoda** [comment]
We fixed this with #7
