### ISSUE TITLE
slim down production build

### ISSUE THREAD

**Issue by markshust** [meteorhacks/meteord#63]
This is an optimization ticket.

I tested out a few meteor docker images, and like the heavy use of this image and the simplicity. However, when comparing it to https://github.com/chriswessels/meteor-tupperware the production build sizes were quite a bit different:
tupperware: 322.1 MB
meteord: 439 MB

It looks like tupperware is doing some sort of cleanup https://github.com/chriswessels/meteor-tupperware/blob/master/includes/scripts/_post_clean.sh

Wanted to hear pros/cons of implementing something like this into meteord.

**Comment by jshimko** [comment]
Already being done (and was specifically influenced by the other repo)
https://github.com/meteorhacks/meteord/blob/master/base/scripts/lib/cleanup.sh

**Comment by jshimko** [comment]
Is it possible that you're leaving out dependencies in Tupperware?  The default is to not install things like PhantomJS, etc.  

https://github.com/chriswessels/meteor-tupperware/blob/master/includes/tupperbuild/main.js#L9-L20

Which is not the case in meteord...

https://github.com/meteorhacks/meteord/blob/master/base/scripts/lib/install_phantomjs.sh

**Comment by markshust** [comment]
Yea I'm using defaults, so it appears PhantomJS isn't getting installed. That may help size also.

**Comment by arunoda** [comment]
I think we have a good balance.

**Comment by markshust** [comment]
Yes, I had build issues with tupperware, so something was missing that is needed (outside phantom). Ok with keeping as is.
