### ISSUE TITLE
BUNDLE_URL authentication

### ISSUE THREAD

**Issue by philcruz** [meteorhacks/meteord#65]
As far as I can tell, BUNDLE_URL needs to be open to the public. Would be nice if BUNDLE_URL could be configured with (AWS) authentication credentials. Perhaps using s3curl.

**Comment by philcruz** [comment]
For my use case, I'm using CodeShip to push to S3 and then using AWS ECS. These support using AWS keys/permissions so I don't need this.

**Comment by philcruz** [comment]
Actually, I do still need this. The meteord script just uses curl so doesn't use the AWS credentials. Reopening...

**Comment by arunoda** [comment]
I don't like to bring to the core. 
If it's not public, try to clone it to locally and mount it.

**Comment by clemenshelm** [comment]
@philcruz How did you solve this in the end?

**Comment by philcruz** [comment]
I didn't solve it. I was pushing to an S3 bucket and I just ended up granting read permissions to all for that bucket. http://blog.philcruz.com/2015/12/continuous-deployment-of-meteor-to.html

**Comment by clemenshelm** [comment]
Cool, thanks for the info!
