### ISSUE TITLE
Errors executing Cordova commands:

### ISSUE THREAD

**Issue by vithanidarpan** [meteorhacks/meteord#71]
$ meteor run android
[[[[[ ~/Desktop/MeteorProjects/demo ]]]]]     

=> Started proxy.  
=> Started MongoDB.  
=> Started your app.                                                            

=> App running at: http://localhost:3000/  
=> Errors executing Cordova commands:         

   While running Cordova app for platform Android with options --emulator:
   Error: Command failed:  
   /home/ibl/Desktop/MeteorProjects/demo/.meteor/local/cordova-build/platforms/android/cordova/run
   --emulator

   /home/ibl/Desktop/MeteorProjects/demo/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   Error code 1 for command:
   /home/ibl/Desktop/MeteorProjects/demo/.meteor/local/cordova-build/platforms/android/gradlew
   with args:
   cdvBuildDebug,-b,/home/ibl/Desktop/MeteorProjects/demo/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1

**Comment by rolivav** [comment]
How did you fix this? I'm having the same error, but with android-device.

**Comment by vithanidarpan** [comment]
I had android sdk problem. First run command with --verbose to find out actual error. For example
run command : meteor run android --verbose
so that you will get actual error in log and then using google you can easily fix it.

**Comment by rolivav** [comment]
Thanks, I did but it didn't say enything out of the ordinary. It ended up being that JAVA_HOME was not set correctly.
