### ISSUE TITLE
Error WebSocket connection

### ISSUE THREAD

**Issue by Jayuda** [meteorhacks/meteord#94]
Hello Guys,
On my meteor app show this error : 
`WebSocket connection to 'ws://..../websocket' failed: Error during WebSocket handshake: Unexpected response code: 400`

What should i do ? Thanks

**Comment by haizi-zh** [comment]
Are you using Meteor behind nginx? When improperly configured, this error might happen. The following article may help you:

http://stackoverflow.com/questions/17014969/meteor-websocket-handshake-error-400-with-nginx
