### ISSUE TITLE
library/meteor not found

### ISSUE THREAD

**Issue by aligg73** [meteorhacks/meteord#98]
Hi,

I pulled your image and ran docker build successfully.
When I issue docker run though, including all the parameter you specified, I get this error:

Unable to find image 'meteor:latest' locally
Pulling repository docker.io/library/meteor
docker: Error: image library/meteor not found.

I am running docker 1.11 on Ubuntu 14.04. Is this a bug or is it related to some local set-up?

Thank you,
Alex

**Comment by jshimko** [comment]
Going to need a little more info to diagnose that.  Can you please share the command(s) you're running and the contents of your Dockerfile?

**Comment by aligg73** [comment]
Thanks.
Dockerfile contains only:
FROM meteorhacks/meteord:onbuild

Commands issued:
docker pull meteorhacks/meteord
docker build -t aligg73/iarchiv-meteor . (from within an existing meteor codebase)

and this one for the run:
docker run -d  
-e ROOT_URL=http://localhost
-e MONGO_URL=mongodbURL
-p 8080:80  
aligg73/iarchiv-meteor

**Comment by jshimko** [comment]
The `docker run` command you have there is split across several lines.  Did you escape the line breaks with slashes? 

``` sh
docker run -d \
  -e ROOT_URL=http://localhost \
  -e MONGO_URL=mongodbURL \
  -p 8080:80 \
  aligg73/iarchiv-meteor
```

**Comment by aligg73** [comment]
Yes i tried that.
I just put everything in one line (with spacing), so the command runs. I pasted it here from my command line and applied some spacing, that's why the backslashes are missing.

**Comment by jshimko** [comment]
That should work.  I suspect you have a typo somewhere because there is no point where Docker should be trying to download `meteor:latest`.  That doesn't even exist. 

Without seeing your code, I unfortunately can't suggest much more.  If you have a public repo, I'd be happy to take a look.

**Comment by aligg73** [comment]
Thanks Jeremy, I double-checked everything and noticed that in my MONGO_URL, there was a space and then the keyword "meteor". So docker run just thought that meteor was to be used....

no wonder it didn't find it!

Many thanks for your help, it was indeed a typo.
